# Trajectories
theta: 45, 90 # initial_theta, final_theta
phi: 45, 135
total_points: 4
r: 6
run_folder: runs/test1/

# Camera
image_width: 100
aspect_ratio: 1
fov: 90
space: schwarzschild
aperture: 2. # It is not used yet
lookfrom: 0., 0., -6.
lookat: 0., 0., 0.
upvector: 0., 1., 0.

# Rendering
antialiasing: 1
evolution_method: verlet
steps: 50000 # 50000 works
initial_timestep: 0.1
background_color: 0.0
debug: True

# Scene
light1_pos: 0., 0., -6
light2_pos: 4., 4., -4

